# samba-dc01 is the container name and samba is the service name in docker-compose file of the samba PDC. Hostname is dc01
# samba-dc02 is the second domain controller joining the domain of dc01. Hostname is dockersamba02
# domain is sam.dom
name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose -f docker-compose.yml build
      - name: Start DC01
        run: docker-compose -f docker-compose.yml up -d samba
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Check network
        run: docker network inspect samba-net
      - name: Check running containers
        run: docker ps -a
      - name: Check logs DC01
        run: docker logs samba-dc01
      - name: Check DC01 NTP
        run: docker exec --tty samba-dc01 /usr/bin/chronyc sources && /usr/bin/chronyc tracking
      - name: Check DC01 config
        run: docker exec --tty samba-dc01 /usr/bin/testparm -vs
      - name: Check DC01 processes
        run: docker exec --tty samba-dc01 /usr/bin/samba-tool processes
      - name: Check DC01 domain
        run: docker exec --tty samba-dc01 /usr/bin/samba-tool domain info 127.0.0.1
      - name: Check DC01 winbindd
        run: docker exec --tty samba-dc01 /usr/bin/wbinfo -u
      - name: Check DC01 DNS
        run: docker exec --tty samba-dc01 /usr/bin/dig +short -t srv _ldap._tcp.sam.dom
      - name: Check DC01 RDNS
        run: docker exec --tty samba-dc01 /usr/bin/dig -x 172.101.1.100
      - name: Check DC01 Host record
        run: docker exec --tty samba-dc01 /usr/bin/host -t A DC01.sam.dom
      - name: Start DC02
        run: docker-compose -f docker-compose.yml up -d samba-join
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Check logs DC02
        run: docker logs samba-dc02
      - name: Check DC02 NTP
        run: docker exec --tty samba-dc02 /usr/bin/chronyc sources && /usr/bin/chronyc tracking
      - name: Check DC02 config
        run: docker exec --tty samba-dc02 /usr/bin/testparm -vs
      - name: Check DC02 processes
        run: docker exec --tty samba-dc02 /usr/bin/samba-tool processes
      - name: Check DC02 domain
        run: docker exec --tty samba-dc02 /usr/bin/samba-tool domain info 127.0.0.1
      - name: Check DC02 winbindd
        run: docker exec --tty samba-dc02 /usr/bin/wbinfo -u
      - name: Check DC02 DNS
        run: docker exec --tty samba-dc02 /usr/bin/dig +short -t srv _ldap._tcp.sam.dom
      - name: Check DC02 RDNS
        run: docker exec --tty samba-dc02 /usr/bin/dig -x 172.101.2.200
      - name: Check DC02 Host record
        run: docker exec --tty samba-dc02 /usr/bin/host -t A dockersamba02.sam.dom
      - name: Check DC02 Host record of DC01
        run: docker exec --tty samba-dc02 /usr/bin/dig +short dc01.sam.dom
      - name: Check DC02 Host record of DC02
        run: docker exec --tty samba-dc02 /usr/bin/dig +short dockersamba02.sam.dom
            
    